queries = { 

    "query_total":""" 
    
    WITH _NOVENTAENOVE AS (
    SELECT IDMOV,DATAMOVIMENTO,STATUS, B.IDMOVDESTINO as 'IDMOV_1198'
    FROM CorporeRM.TMOV A
    LEFT JOIN CORPORERM.TMOVRELAC B
    ON A.IDMOV = B.IDMOVORIGEM 
    WHERE CODTMV = '1.1.99' AND YEAR(DATAMOVIMENTO) BETWEEN 2020 AND 2025)

    , FINAL AS(
    SELECT A.*,B.IDMOVDESTINO as 'IDMOV_1223' FROM _NOVENTAENOVE A
    LEFT JOIN CORPORERM.TMOVRELAC B
    ON A.IDMOV_1198 = B.IDMOVORIGEM)
    
    ,TVEN AS (SELECT CODVEN,NOME FROM CorporeRM.TVEN)

    ,GDEPTO AS (SELECT CODDEPARTAMENTO, NOME FROM CorporeRM.GDEPTO WHERE CODFILIAL = 1)

    , TOTAL AS (
    SELECT 
    
    B.IDMOV AS 'IDENTIFICADOR'
    ,B.CODTMV AS 'TIPO'
    ,B.DATAEMISSAO
    ,B.NUMEROMOV AS 'NUMMOV'
    ,B.VALORBRUTOORIG AS 'V_DOCUMENTO'
    ,B.CODCFO
    ,C.NOME AS 'RAZÃOSOCIAL'
    ,C.CGCCFO AS 'CPF/CNPJ'
    ,C.CODETD AS 'UF CLI/FOR'
    ,B.CAMPOLIVRE1 AS 'CONTRATORM'
    ,E.PROCESSO
    ,F.NOME AS 'ER'
    ,G.NOME AS 'USUARIO'
    ,B.DATACANCELAMENTOMOV
    ,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN 0 ELSE -B.VALORBRUTOORIG END AS 'V_ESTORNADO_CANCELADO'
    ,CASE WHEN B.DATACANCELAMENTOMOV IS NULL OR B.DATACANCELAMENTOMOV = '' THEN NULL ELSE FORMAT(B.DATACANCELAMENTOMOV, 'MMMM/yyyy','PT-BR') END AS 'MES_CANCELAMENTO'
    ,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL ELSE B.VALORBRUTOORIG END AS 'V_PROVISIONADO'
    ,UPPER(FORMAT(B.DATAEMISSAO, 'yyyy','PT-BR')) AS 'ANO_PROVISAO'
    ,UPPER(FORMAT(B.DATAEMISSAO, 'MMMM/yyyy','PT-BR')) AS 'MES_PROVISAO'
    ,CASE WHEN H.NUMEROMOV IS NULL OR H.NUMEROMOV = '' THEN 0 ELSE B.VALORBRUTOORIG END AS 'V_PAGO'
    ,H.NUMEROMOV as 'NF'
    ,CASE WHEN B.DATAEMISSAO <= B.DATACANCELAMENTOMOV THEN NULL WHEN H.NUMEROMOV IS NULL THEN B.VALORBRUTOORIG ELSE NULL END AS 'MOVIMENTOS_PENDENTES_PAGAMENTO'
    ,D.NOME AS CONTRATO
    ,CASE WHEN D.CODSTACNT = '00001' THEN 'ABERTO' WHEN D.CODSTACNT = '00002' THEN 'ENCERRADO' WHEN D.CODSTACNT = '00008' THEN 'ENCERRADO POR VIGENCIA' ELSE 'ABERTO' END AS 'STCONTRATO'
    ,I.NOME  AS GESTOR
    ,J.NOME AS GERENTE
    ,K.NOME AS 'UNIDADE'
    FROM FINAL A
    LEFT JOIN CorporeRM.TMOV B
    ON A.IDMOV = B.IDMOV
    LEFT JOIN CorporeRM.FCFO C
    ON B.CODCFO = C.CODCFO
    LEFT JOIN CorporeRM.TCNT D
    ON B.CAMPOLIVRE1 COLLATE Latin1_General_CI_AI = D.CODIGOCONTRATO
    LEFT JOIN CorporeRM.TCNTCOMPL E
    ON D.IDCNT = E.IDCNT
    LEFT JOIN GDEPTO F
    ON B.CODDEPARTAMENTO COLLATE Latin1_General_CI_AI = F.CODDEPARTAMENTO
    LEFT JOIN CorporeRM.TVEN G
    ON (B.CODVEN1 = G.CODVEN OR (B.CODVEN1 IS NULL AND B.CODVEN2 = G.CODVEN))
    LEFT JOIN CorporeRM.TMOV H
    ON A.IDMOV_1223 = H.IDMOV
    LEFT JOIN TVEN I
    ON D.CODVEN COLLATE SQL_Latin1_General_CP1_CI_AI = I.CODVEN
    LEFT JOIN TVEN J
    ON D.CODVEN2 COLLATE SQL_Latin1_General_CP1_CI_AI = J.CODVEN
    LEFT JOIN GDEPTO K
    ON D.CODDEPARTAMENTO COLLATE Latin1_General_CI_AS = K.CODDEPARTAMENTO
    )
        
    SELECT * FROM TOTAL

    """


}